"""initial schema: agents, world_tiles, events, simulation_state

Revision ID: 37a96d923058
Revises: 
Create Date: 2026-04-12 13:50:04.361734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37a96d923058'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), server_default='idle', nullable=False),
    sa.Column('hunger', sa.Float(), server_default='100.0', nullable=False),
    sa.Column('energy', sa.Float(), server_default='100.0', nullable=False),
    sa.Column('social', sa.Float(), server_default='100.0', nullable=False),
    sa.Column('health', sa.Float(), server_default='100.0', nullable=False),
    sa.Column('age', sa.Integer(), server_default='0', nullable=False),
    sa.Column('alive', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index('idx_agents_alive', ['alive'], unique=False, postgresql_where=sa.text('alive = TRUE'))
        batch_op.create_index('idx_agents_position', ['x', 'y'], unique=False)

    op.create_table('simulation_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_tick', sa.Integer(), server_default='0', nullable=False),
    sa.Column('running', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('speed', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('world_width', sa.Integer(), nullable=False),
    sa.Column('world_height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('world_tiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('terrain', sa.String(length=20), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=True),
    sa.Column('resource_amount', sa.Float(), server_default='0.0', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('x', 'y', name='uq_world_tiles_xy')
    )
    with op.batch_alter_table('world_tiles', schema=None) as batch_op:
        batch_op.create_index('idx_tiles_resource', ['resource_type'], unique=False, postgresql_where=sa.text('resource_type IS NOT NULL'))

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_events_agent_id', ['agent_id'], unique=False)
        batch_op.create_index('idx_events_event_type', ['event_type'], unique=False)
        batch_op.create_index('idx_events_tick', ['tick'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('idx_events_tick')
        batch_op.drop_index('idx_events_event_type')
        batch_op.drop_index('idx_events_agent_id')

    op.drop_table('events')
    with op.batch_alter_table('world_tiles', schema=None) as batch_op:
        batch_op.drop_index('idx_tiles_resource', postgresql_where=sa.text('resource_type IS NOT NULL'))

    op.drop_table('world_tiles')
    op.drop_table('simulation_state')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index('idx_agents_position')
        batch_op.drop_index('idx_agents_alive', postgresql_where=sa.text('alive = TRUE'))

    op.drop_table('agents')
    # ### end Alembic commands ###
